on:
    workflow_dispatch:
    push:
        branches:
            - master
            - fix-cd

jobs:
    create-tag:
      uses: ./.github/workflows/step_create_tag.yaml
      secrets: inherit
    test-job:
      runs-on: ubuntu-22.04
      needs:
        - create-tag
      steps:
        - name: get-output
          run: echo ${{ needs.create-tag.outputs.tag-exists }}
    create-release:
      needs:
        - create-tag
      if: ${{ !needs.create-tag.outputs.tag-exists }}
      uses: ./.github/workflows/step_create_release.yaml
      secrets: inherit
