on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    create-tag:
      uses: ./.github/workflows/step_create_tag.yaml
      secrets: inherit
    create-release:
      if: ${{ !needs.create-tag.outputs.tag-exists }}
      needs:
        - create-tag
      if: ${{ !needs.create-tag.outputs.tag-exists }}
      uses: ./.github/workflows/step_create_release.yaml
      secrets: inherit
