on:
    workflow_call:


jobs:
    create_release:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Install Poetry
              uses: snok/install-poetry@v1
            - name: Build wheel
              run: poetry build
            - name: get_version
              uses: mikefarah/yq@master
              with:
                cmd: yq -oy ".tool.poetry.version" ./pyproject.toml
            - uses: ncipollo/release-action@v1
              with:
                artifacts: "dist/*"
                tag: v${{ steps.get_version.outputs.result }}
