on:
  workflow_call:
    outputs:
      tag-exists:
        description: "True if the tag already exist, false otherwise"
        value: ${{ jobs.create-tag.outputs.tag-exists }}

jobs:
    create-tag:
        runs-on: ubuntu-22.04
        outputs:
          tag-exists: ${{ env.TAG_EXISTS }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: get_version
              id: get_version
              uses: mikefarah/yq@master
              with:
                cmd: yq -oy ".tool.poetry.version" ./pyproject.toml
            - uses: rickstaa/action-create-tag@v1.6.2
              id: "tag_create"
              with:
                tag: "v${{ steps.get_version.outputs.result }}"
                tag_exists_error: false
                message: ""
