on:
  workflow_call:

jobs:
    create-tag:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: get_version
              id: get_version
              uses: mikefarah/yq@master
              with:
                cmd: yq -oy ".tool.poetry.version" ./pyproject.toml
            - uses: rickstaa/action-create-tag@v1
              id: "tag_create"
              with:
                tag: "v${{ steps.get_version.outputs.result }}"
                tag_exists_error: true
                message: ""
            - name: cancelling
              if: ${{steps.tag_create.outputs.tag_exists}}
              uses: andymckay/cancel-action@0.3
